// Getters
export const PEMINJAM = 'PEMINJAM'
export const PEMINJAMANDATA = 'PEMINJAMANDATA'

// Mutations
export const MUTATE_PEMINJAM = 'MUTATE_PEMINJAM'
export const MUTATE_PEMINJAMANDATA = 'MUTATE_PEMINJAMANDATA'

// Actions
export const UPDATE_PEMINJAM = 'UPDATE_PEMINJAM'
export const UPDATE_PEMINJAMANDATA = 'UPDATE_PEMINJAMANDATA'
